import { createHash } from 'node:crypto'
import { sep } from 'node:path'
import { splitOptionArgs, insertOptionArgs } from '../claude-args'

/**
 * Pure decisions of the companion mod's staging (P1W2 §7.3). The fs shell is `staging.ts`.
 * Nothing here touches the disk, the environment or Electron.
 */

/**
 * What a staged tree may contain (MOD-9). Never staged: `tests/`, `api-surface.json`,
 * `tsconfig.json`, `.gitignore`, and `.claude-plugin/types/` (the engine writes that one on load).
 */
export const STAGE_ALLOW = ['.claude-plugin/plugin.json', 'types/', 'hooks/'] as const

/** The generated module is written by staging itself, never copied from the source tree. */
const GENERATED = 'hooks/coords.gen.ts'

export function isStageable(rel: string): boolean {
  if (rel === GENERATED) return false
  if (rel.split('/').some((seg) => seg === '..' || seg === '.DS_Store')) return false
  return STAGE_ALLOW.some((a) => (a.endsWith('/') ? rel.startsWith(a) : rel === a))
}

/** `all` are POSIX-style paths relative to the plugin root. */
export function stageFileList(all: readonly string[]): string[] {
  return all.filter(isStageable)
}

// ---- Generated coordinates (contract §23) --------------------------------------------

/**
 * The export list of `hooks/coords.gen.ts`. A wave that needs another baked value adds a field
 * here and to `scripts/ci/render-coords.mjs` (its twin) in its own change.
 */
export interface Coords {
  RENDEZVOUS_PATH: string
  MOD_VERSION: string
  STAGED_AT: number
}

/** Every value goes through `JSON.stringify`, so a quote or backslash in a path cannot escape. */
export function renderCoords(fields: Coords): string {
  const lines = ['// GENERATED by Harnu staging. Never edit by hand.']
  for (const [name, value] of Object.entries(fields)) {
    lines.push(`export const ${name} = ${JSON.stringify(value)}`)
  }
  return lines.join('\n') + '\n'
}

// ---- Stage identity -------------------------------------------------------------------

const sha = (s: string): string => createHash('sha256').update(s).digest('hex')

/** Hex digest over the allowed source files plus the rendered coordinates; order-independent. */
export function stageManifest(files: { rel: string; sha256: string }[], coords: string): string {
  const lines = [...files]
    .sort((a, b) => (a.rel < b.rel ? -1 : a.rel > b.rel ? 1 : 0))
    .map((f) => `${f.rel}\0${f.sha256}`)
  return sha(`${lines.join('\n')}\n\0coords\0${sha(coords)}`)
}

/**
 * `<modVersion>` for a fresh or identical stage; otherwise a sibling `<modVersion>.<hash8>` so
 * the existing tree is never written (a write hot-reloads it in every live session, smoke A5).
 */
export function stageKeyFor(modVersion: string, wanted: string, onDisk: string | null): string {
  return onDisk === null || onDisk === wanted ? modVersion : `${modVersion}.${wanted.slice(0, 8)}`
}

/**
 * Insert `--plugin-dir <dir>` immediately before the first existing `--plugin-dir` of the option
 * portion, or at its end when there is none, so the companion is first even when the user's own
 * Claude Boot args carry one (MOD-9). Returns the argv unchanged when the directory is already
 * there. Only the option portion is scanned: a pre-prompt quoting the flag proves nothing.
 */
export function insertCompanionPluginDir(args: readonly string[], dir: string): string[] {
  const { options, promptTail } = splitOptionArgs(args)
  for (let i = 0; i < options.length - 1; i++) {
    if (options[i] === '--plugin-dir' && options[i + 1] === dir) return [...args]
  }
  if (options.includes(`--plugin-dir=${dir}`)) return [...args]
  const first = options.findIndex((o) => o === '--plugin-dir' || o.startsWith('--plugin-dir='))
  if (first < 0) return insertOptionArgs(args, ['--plugin-dir', dir])
  return [...options.slice(0, first), '--plugin-dir', dir, ...options.slice(first), ...promptTail]
}

// ---- Garbage collection ---------------------------------------------------------------

export const GC_MAX_AGE_MS = 14 * 24 * 60 * 60 * 1000

export interface StageEntry {
  /** Directory name under `<userData>/companion/`: `<modVersion>` or `<modVersion>.<hash8>`. */
  key: string
  /** The plugin directory inside it (what `--plugin-dir` receives). */
  dir: string
  /** mtime of its `.stamp`. */
  stampMs: number
}

const within = (path: string, dir: string): boolean =>
  path === dir || path.startsWith(dir + sep) || path.startsWith(dir + '/')

/**
 * Stage keys that may be removed at boot: not the current directory, not named by a pin or a
 * spawn record, and stamped more than 14 days ago. Pins are by DIRECTORY, because a stage key
 * is not always the version. Never run during a session.
 */
export function gcVictims(x: {
  entries: readonly StageEntry[]
  currentDir: string | null
  pinnedDirs: readonly string[]
  nowMs: number
  maxAgeMs?: number
}): string[] {
  const max = x.maxAgeMs ?? GC_MAX_AGE_MS
  return x.entries
    .filter((e) => e.dir !== x.currentDir)
    .filter((e) => !x.pinnedDirs.some((p) => within(p, e.dir)))
    .filter((e) => x.nowMs - e.stampMs > max)
    .map((e) => e.key)
}

// ---- Developer hot-reload mode --------------------------------------------------------

/**
 * `HARNU_COMPANION_DEV=1` points the sessions of ONE unpackaged instance at the repository
 * folder (§7.5). Two instances would rewrite the single `coords.gen.ts` and reload each other's
 * sessions onto the wrong endpoint, so a live lock held by another pid forces normal staging.
 */
export function devModeDecision(x: {
  flag: boolean
  packaged: boolean
  lock: { pid: number } | null
  selfPid: number
  pidAlive: (pid: number) => boolean
}): { mode: 'repo' | 'stage'; warn?: string } {
  if (!x.flag || x.packaged) return { mode: 'stage' }
  if (x.lock && x.lock.pid !== x.selfPid && x.pidAlive(x.lock.pid)) {
    return {
      mode: 'stage',
      warn: `HARNU_COMPANION_DEV ignored: resources/companion is held by pid ${x.lock.pid}; staging normally`
    }
  }
  return { mode: 'repo' }
}
