import { describe, it, expect } from 'vitest'
import {
  extractCommandName,
  stripMetaWrappers,
  firstRealPrompt,
  rootRepoPath
} from '../src/main/claude-reader-derive'

describe('extractCommandName', () => {
  it('pulls the command name out of a slash-command wrapper', () => {
    expect(
      extractCommandName(
        '<command-message>foo</command-message><command-name>dtk:smart-commit</command-name>'
      )
    ).toBe('dtk:smart-commit')
  })
  it('trims whitespace inside the tag', () => {
    expect(extractCommandName('<command-name>  /review  </command-name>')).toBe('/review')
  })
  it('returns empty string when there is no command-name tag', () => {
    expect(extractCommandName('just a normal prompt')).toBe('')
  })
})

describe('stripMetaWrappers', () => {
  it('removes a system-reminder block and keeps the real prompt', () => {
    const raw = '<system-reminder>session context blah</system-reminder>\nFix the bug in pty.ts'
    expect(stripMetaWrappers(raw)).toBe('Fix the bug in pty.ts')
  })
  it('removes command-message / command-name / command-args / local-command-stdout blocks', () => {
    const raw =
      '<command-message>x is running</command-message><command-name>x</command-name><command-args>y</command-args><local-command-stdout>out</local-command-stdout>'
    expect(stripMetaWrappers(raw)).toBe('')
  })
  it('drops an unclosed trailing system-reminder defensively', () => {
    expect(stripMetaWrappers('Real prompt\n<system-reminder>truncated...')).toBe('Real prompt')
  })
  it('collapses internal whitespace runs and trims', () => {
    expect(stripMetaWrappers('  hello   world  ')).toBe('hello world')
  })
  // BUG-77 — this wrapper was the only meta block left unstripped, so a session
  // whose first turn ran a local command was labelled with the caveat sentence
  // itself instead of falling through to the real prompt.
  it('removes a local-command-caveat block', () => {
    const raw =
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>\nFix the bug in pty.ts'
    expect(stripMetaWrappers(raw)).toBe('Fix the bug in pty.ts')
  })
  it('leaves nothing behind when the turn is only a caveat', () => {
    expect(stripMetaWrappers('<local-command-caveat>Caveat: …</local-command-caveat>')).toBe('')
  })
})

describe('firstRealPrompt', () => {
  it('returns the command name when the first turn is a slash command', () => {
    expect(
      firstRealPrompt([
        '<command-message>r</command-message><command-name>dtk:smart-commit</command-name>'
      ])
    ).toBe('dtk:smart-commit')
  })
  it('skips a pure system-reminder turn and uses the next real prompt', () => {
    expect(
      firstRealPrompt(['<system-reminder>only context</system-reminder>', 'Actually fix it'])
    ).toBe('Actually fix it')
  })
  it('strips a leading system-reminder embedded in the first turn', () => {
    expect(firstRealPrompt(['<system-reminder>ctx</system-reminder>Do the thing'])).toBe(
      'Do the thing'
    )
  })
  it('truncates to 120 chars', () => {
    const long = 'a'.repeat(200)
    const out = firstRealPrompt([long])
    expect(out.length).toBe(120)
  })
  it('returns empty string when nothing real is found', () => {
    expect(
      firstRealPrompt([
        '<system-reminder>ctx</system-reminder>',
        '<command-message>x</command-message>'
      ])
    ).toBe('')
    expect(firstRealPrompt([])).toBe('')
  })
  // Moved from the deleted renderer mirror's suite (sidebar-liveness U3a): the
  // watcher now computes `firstPromptCandidate` with this function.
  it('never returns the local-command caveat as a label (BUG-77)', () => {
    const caveat =
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>'
    expect(firstRealPrompt([caveat])).toBe('')
  })
  it('falls through a caveat-only turn to the next real prompt', () => {
    expect(
      firstRealPrompt([
        '<local-command-caveat>Caveat: …</local-command-caveat>',
        'the actual question'
      ])
    ).toBe('the actual question')
  })
  it('returns empty for a whitespace-only turn', () => {
    expect(firstRealPrompt(['   '])).toBe('')
  })
})

describe('rootRepoPath', () => {
  it('strips a Claude worktree suffix down to the repo root', () => {
    expect(rootRepoPath('/home/u/Code/DemoApp/.claude/worktrees/funny-bohr-cfce08')).toBe(
      '/home/u/Code/DemoApp'
    )
  })
  it('returns a non-worktree cwd unchanged', () => {
    expect(rootRepoPath('/home/u/Code/DemoApp')).toBe('/home/u/Code/DemoApp')
  })
  it('returns empty string unchanged', () => {
    expect(rootRepoPath('')).toBe('')
  })
})
