import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

/**
 * THIRD-PARTY-NOTICES.md is generated by `scripts/gen-third-party-notices.mjs` and
 * shipped with every build (MIT, BSD and OFL all require the notice to travel with the
 * binary). This catches the common drift: a runtime dependency added to package.json
 * without regenerating the file.
 */
const ROOT = resolve(__dirname, '..')
const notices = readFileSync(resolve(ROOT, 'THIRD-PARTY-NOTICES.md'), 'utf8')
const pkg = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8')) as {
  dependencies: Record<string, string>
}

describe('THIRD-PARTY-NOTICES.md', () => {
  it.each(Object.keys(pkg.dependencies))('lists the runtime dependency %s', (name) => {
    expect(notices).toContain(`| ${name} |`)
  })

  it('lists the renderer packages Vite bundles from devDependencies', () => {
    expect(notices).toContain('| vue |')
    expect(notices).toContain('| tailwindcss |')
  })

  it('carries the bundled font licenses', () => {
    expect(notices).toContain('SIL OPEN FONT LICENSE Version 1.1')
    expect(notices).toContain('Nerd Fonts')
  })

  it('is shipped with the packaged app, next to LICENSE', () => {
    const builder = readFileSync(resolve(ROOT, 'electron-builder.yml'), 'utf8')
    expect(builder).toContain("from: 'THIRD-PARTY-NOTICES.md'")
    expect(builder).toContain("from: 'LICENSE'")
  })
})
