// Twin of `renderCoords` in src/main/companion/staging-core.ts. The `mod` step runs as plain
// Node and cannot import TypeScript, so the generator exists twice; one vitest case
// (tests/companion/staging-core.test.ts, "the mjs twin equals the renderer") pins them equal.
// Change both together.

const KEY = /^[A-Z][A-Z0-9_]*$/

/** @param {Record<string, unknown>} fields export name to JSON-serializable value */
export function renderCoords(fields) {
  const lines = ['// GENERATED by Harnu staging. Never edit by hand.']
  for (const [name, value] of Object.entries(fields)) {
    if (!KEY.test(name)) throw new Error(`bad coordinate name: ${name}`)
    lines.push(`export const ${name} = ${JSON.stringify(value)}`)
  }
  return lines.join('\n') + '\n'
}
